SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `inventario_db`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `aseo`
--

CREATE TABLE `aseo` (
  `CODIGO` varchar(255) DEFAULT NULL,
  `CODIGO_BARRAS` varchar(255) DEFAULT NULL,
  `PRODUCTO` varchar(255) NOT NULL,
  `CANT` int(11) DEFAULT 0,
  `UNIDAD` enum('CAJA','UNIDAD','FRASCO','PAQUETE','PAR','PACA') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `aseo`
--

INSERT INTO `aseo` (`CODIGO`, `CODIGO_BARRAS`, `PRODUCTO`, `CANT`, `UNIDAD`) VALUES
('NCSA001', '*NCSA001*', 'PAPELERA VAIVEN ESTRA NEGRA 53 LITROS ORIGINAL', 12, 'UNIDAD'),
('NCSA002', '*NCSA002*', 'PAPELERA VAIVEN BLANCA ESTRA 53 LITROS ORGINAL', 12, 'UNIDAD'),
('NCSA003', '*NCSA003*', 'PAPELERA VAIVEN ESTRA VERDE 53 LIRTOS ORIGINAL', 12, 'UNIDAD'),
('NCSA004', '*NCSA004*', 'ESTRUCTURA PUNTO ECOLOGICO x3 PUESTOS DE 53 LITROS ', 12, 'UNIDAD'),
('NCSA005', '*NCSA005*', 'BOLSA DE BASURA NEGRA PAPELERA 50*60 x6 UNIDADES', 24, 'PAQUETE'),
('NCSA006', '*NCSA006*', 'BOLSA DE BASURA VERDE 70*100 x6 UNIDADES CAL 3', 12, 'UNIDAD'),
('NCSA007', '*NCSA007*', 'BOLSA DE BASURA NEGRA INDUSTRIAL 70*100 x6 UNIDADES', 36, 'PAQUETE'),
('NCSA008', '*NCSA008*', 'BOLSA DE BASURA VERDE 100*120 x6 UNIDADES', 24, 'PAQUETE'),
('NCSA009', '*NCSA009*', 'TOALLA PARA MANOS NATURAL Z-FOLD *150 UNIDADES', 24, 'PAQUETE'),
('NCSA010', '*NCSA010*', 'SERVILLETAS FAVORITA *300 UNIDADES', 12, 'PAQUETE'),
('NCSA011', '*NCSA011*', 'JABON BARRA REY 300 GRAMOS', 24, 'UNIDAD'),
('NCSA012', '*NCSA012*', 'PAPEL HIGENICO JUMBO SANITISU *4 ROLLOS', 6, 'PACA'),
('NCSA013', '*NCSA013*', 'GUANTE INDUSTRIAL  CALIBRE 35 TALLA 7½', 6, 'PAR'),
('NCSA014', '*NCSA014*', 'GUANTE INDUSTRIAL  CALIBRE 35 TALLA 8', 6, 'PAR'),
('NCSA015', '*NCSA015*', 'GUANTE INDUSTRIAL PROTEX CALIBRE 35 TALLA 9', 6, 'PAR'),
('NCSA016', '*NCSA016*', 'GUANTE DOMESTICO RUBBERPLUS CALIBRE 25 TALLA 7½', 6, 'PAR'),
('NCSA017', '*NCSA017*', 'GUANTE DOMESTICO RUBBERPLUS CALIBRE 25 TALLA 8', 6, 'PAR'),
('NCSA018', '*NCSA018*', 'LIMPION EN TOALLA BLANCA 45CM * 50CM', 12, 'UNIDAD'),
('NCSA019', '*NCSA019*', 'VASO DE CARTON  7 ONZ  *50  UNIDADES', 12, 'PAQUETE'),
('NCSA020', '*NCSA020*', 'ESPONJA LA MAQUINA *2 UND', 6, 'PAQUETE'),
('NCSA021', '*NCSA021*', 'ABRASIVO REGULAR', 12, 'UNIDAD'),
('NCSA022', '*NCSA022*', 'CREMA LAVAPLATOS AXION * 850 gr', 5, 'UNIDAD'),
('NCSA023', '*NCSA023*', 'MANGO METALICO 140CM CON ROSCA BLANCO', 4, 'UNIDAD'),
('NCSA024', '*NCSA024*', 'MANGO METALICO 140CM CON ROSCA AZUL', 4, 'UNIDAD'),
('NCSA025', '*NCSA025*', 'MANGO METALICO 140CM CON ROSCA ROJO', 4, 'UNIDAD');

--
-- Disparadores `aseo`
--
DELIMITER $$
CREATE TRIGGER `generar_codBarras_aseo` BEFORE INSERT ON `aseo` FOR EACH ROW BEGIN
    SET NEW.CODIGO_BARRAS = CONCAT('*', NEW.CODIGO, '*');
END
$$
DELIMITER ;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `ferreteria`
--

CREATE TABLE `ferreteria` (
  `CODIGO` varchar(255) DEFAULT NULL,
  `CODIGO_BARRAS` varchar(255) DEFAULT NULL,
  `PRODUCTO` varchar(255) NOT NULL,
  `CANT` int(11) DEFAULT 0,
  `UNIDAD` enum('CAJA','UNIDAD','FRASCO','PAQUETE','PAR','PACA') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `ferreteria`
--

INSERT INTO `ferreteria` (`CODIGO`, `CODIGO_BARRAS`, `PRODUCTO`, `CANT`, `UNIDAD`) VALUES
('NCSF001', '*NCSF001*', 'TORNILLO PUNTA BROCA 8x1', 100, 'UNIDAD'),
('NCSF002', '*NCSF002*', 'TACO LUMINEX 20 AMP', 2, 'UNIDAD'),
('NCSF003', '*NCSF003*', 'TACO TRIFASICO 40A LUMINEX', 1, 'UNIDAD'),
('NCSF004', '*NCSF004*', 'ACOPLE LAVAMANOS FLEX METALICA', 1, 'UNIDAD'),
('NCSF005', '*NCSF005*', 'SILICONA TUBO SISTA', 2, 'UNIDAD'),
('NCSF006', '*NCSF006*', 'PIPA GAS PESASDA PROPANO', 1, 'UNIDAD'),
('NCSF007', '*NCSF007*', 'NIPLE GALVANIZADO 3/8\"\"', 3, 'UNIDAD'),
('NCSF008', '*NCSF008*', 'ABRAZADERA 1/2\" TITAN\"', 2, 'UNIDAD'),
('NCSF009', '*NCSF009*', 'CABLE DE RED C6 EXTERIOR COBRE', 305, 'UNIDAD'),
('NCSF010', '*NCSF010*', 'PEGANTE GASTOP FUERZA ALTA 10g', 1, 'UNIDAD'),
('NCSF011', '*NCSF011*', 'PEGANTE GASTOP FUERZA MEDIANA 10g', 1, 'UNIDAD'),
('NCSF012', '*NCSF012*', 'ADAPTADOR MACHO 1/2 PE-AL-PE', 3, 'UNIDAD'),
('NCSF013', '*NCSF013*', 'ADAPTADOR HEMBRA 1/2 PE-AL-PE', 3, 'UNIDAD'),
('NCSF014', '*NCSF014*', 'UNION 1/2\" GALVANIZADA\"', 3, 'UNIDAD'),
('NCSF015', '*NCSF015*', 'CODO 1/2\" GALVANIZADO\"', 3, 'UNIDAD'),
('NCSF016', '*NCSF016*', 'COPA REDUCCION GALV 1/2 x 3/8', 2, 'UNIDAD'),
('NCSF017', '*NCSF017*', 'BUSHING 1/2 x 3/8', 2, 'UNIDAD'),
('NCSF018', '*NCSF018*', 'RECOLECTOR DE FRUTA', 1, 'UNIDAD'),
('NCSF019', '*NCSF019*', 'ACOPLE LAVAMANOS LARGO GRIVAL', 4, 'UNIDAD'),
('NCSF020', '*NCSF020*', 'CHAZO CAIMAN 1/4\"\"', 100, 'UNIDAD'),
('NCSF021', '*NCSF021*', 'NO MAS CLAVOS TUBO', 2, 'UNIDAD'),
('NCSF022', '*NCSF022*', 'EXTENSION X2MTS PESADA', 5, 'UNIDAD'),
('NCSF023', '*NCSF023*', 'CINTA ASFALTICA 20CM x 5MTS ', 4, 'UNIDAD'),
('NCSF024', '*NCSF024*', 'TORNILLO PUNTA BROCA 8x1 ', 100, 'UNIDAD');

--
-- Disparadores `ferreteria`
--
DELIMITER $$
CREATE TRIGGER `generar_codBarras_ferreteria` BEFORE INSERT ON `ferreteria` FOR EACH ROW BEGIN
    SET NEW.CODIGO_BARRAS = CONCAT('*', NEW.CODIGO, '*');
END
$$
DELIMITER ;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `papeleria`
--

CREATE TABLE `papeleria` (
  `CODIGO` varchar(255) NOT NULL,
  `CODIGO_BARRAS` varchar(255) DEFAULT NULL,
  `PRODUCTO` varchar(255) NOT NULL,
  `CANT` bigint(255) NOT NULL,
  `UNIDAD` enum('UNIDAD','CAJA','EMPAQUE','PACA','PAR','FRASCO') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `papeleria`
--

INSERT INTO `papeleria` (`CODIGO`, `CODIGO_BARRAS`, `PRODUCTO`, `CANT`, `UNIDAD`) VALUES
('NCSP0001', '*NCSP0001*', 'MARCADOR BORRABLE RECARGABLE OE-506 ROJO', 10, 'UNIDAD'),
('NCSP0002', '*NCSP0002*', 'MARCADOR BORRABLE RECARGABLE OE-506 NEGRO', 10, 'UNIDAD'),
('NCSP0003', '*NCSP0003*', 'BORRADOR MAGNETICO PARA TABLERO ACRILICO', 5, 'UNIDAD'),
('NCSP0004', '*NCSP0004*', 'GANCHO LEGAJADOR PLASTICO RANK REF 201 *20 UND', 3, 'CAJA'),
('NCSP0005', '*NCSP0005*', 'TINTA PARA SELLO PELIKAN * 30 CC NEGRA', 3, 'FRASCO'),
('NCSP0006', '*NCSP0006*', 'CHINCHE TRITON *50 UNIDADES', 3, 'CAJA'),
('NCSP0007', '*NCSP0007*', 'ARCHIVADOR AZ CARTA OYF PLAST', 10, 'UNIDAD'),
('NCSP0008', '*NCSP0008*', 'ARCHIVADOR AZ OFICIO OYF PLASTIFICADO', 10, 'UNIDAD');

--
-- Disparadores `papeleria`
--
DELIMITER $$
CREATE TRIGGER `generar_codBarras_papeleria` BEFORE INSERT ON `papeleria` FOR EACH ROW BEGIN
    SET NEW.CODIGO_BARRAS = CONCAT('*', NEW.CODIGO, '*');
END
$$
DELIMITER ;

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `aseo`
--
ALTER TABLE `aseo`
  ADD UNIQUE KEY `CODIGO` (`CODIGO`),
  ADD UNIQUE KEY `CODIGO_BARRAS` (`CODIGO_BARRAS`);

--
-- Indices de la tabla `ferreteria`
--
ALTER TABLE `ferreteria`
  ADD UNIQUE KEY `CODIGO` (`CODIGO`),
  ADD UNIQUE KEY `CODIGO_BARRAS` (`CODIGO_BARRAS`);

--
-- Indices de la tabla `papeleria`
--
ALTER TABLE `papeleria`
  ADD PRIMARY KEY (`CODIGO`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
